bot:
  token: insert bot token here
  censor: говнокод,fuck,shit
exp:
  timer: 15
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/discordBot?currentSchema=bot
    username: player
    password: player
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect